# stages-gen-usage.yml
# Reusable stages for GenUsage pipelines (dev/prod)

parameters:
  - name: StageName
    type: string
    default: GenerateUsage
  - name: StageDisplayName
    type: string
    default: Generate usage artifacts
  - name: BuildType
    type: string
    default: "dev"
stages:
  - stage: ${{ parameters.StageName }}
    displayName: ${{ parameters.StageDisplayName }}
    jobs:
      - job: generate_nuget_usage_artifact
        displayName: Generate nuget usage artifact
        timeoutInMinutes: 0
        cancelTimeoutInMinutes: 5
        steps:
          - template: /pipelines/templates/gen-usage-nuget.yml@self
            parameters:
              BuildType: ${{ parameters.BuildType }}

      - job: generate_planner_usage_artifact
        displayName: Generate planner usage artifact
        timeoutInMinutes: 0
        cancelTimeoutInMinutes: 5
        steps:
          - template: /pipelines/templates/gen-usage-planner.yml@self
            parameters:
              BuildType: ${{ parameters.BuildType }}

      - job: generate_usage_artifact
        displayName: Generate usage artifact
        dependsOn:
          - generate_nuget_usage_artifact
          - generate_planner_usage_artifact
        timeoutInMinutes: 0
        cancelTimeoutInMinutes: 5
        templateContext:
          outputs:
            - output: pipelineArtifact
              displayName: Publish GenUsage Artifact
              targetPath: $(Build.ArtifactStagingDirectory)/${{ parameters.BuildType }}/publish-gen-usage
              artifactName: ${{ parameters.BuildType }}-drop
        steps:
          - template: /pipelines/templates/steps-gen-usage.yml@self
            parameters:
              BuildType: ${{ parameters.BuildType }}