# stages-gen-usage.yml
# Reusable stages for GenUsage pipelines (dev/prod)

parameters:
  - name: StageName
    type: string
    default: GenerateUsage
  - name: StageDisplayName
    type: string
    default: Generate usage artifacts
  - name: BuildType
    type: string
    default: "dev"
stages:
  - stage: ${{ parameters.StageName }}
    displayName: ${{ parameters.StageDisplayName }}
    jobs:
      - job: generate_and_publish_usage_artifact
        displayName: Generate and publish usage artifacts
        timeoutInMinutes: 0
        cancelTimeoutInMinutes: 5
        templateContext:
          outputs:
            - output: pipelineArtifact
              displayName: Publish GenUsage Artifact
              targetPath: $(Build.ArtifactStagingDirectory)/${{ parameters.BuildType }}
              artifactName: ${{ parameters.BuildType }}-drop
        steps:
          - template: /pipelines/templates/gen-usage-nuget.yml@self
            parameters:
              BuildType: ${{ parameters.BuildType }}
          - template: /pipelines/templates/gen-usage-planner.yml@self
            parameters:
              BuildType: ${{ parameters.BuildType }}
          - template: /pipelines/templates/steps-gen-usage.yml@self
            parameters:
              BuildType: ${{ parameters.BuildType }}