trigger:
  branches:
    include:
      - main
  paths:
    include:
      - pipelines/build-telemetry.yml
      - src/NetUpgradePlannerTelemetry/**

name: $(date:yyyyMMdd)$(rev:.r)

resources:
  repositories:
    - repository: self
      type: git
      ref: main
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: AzurePipelines-EO
        image: 1ESPT-Windows2022
        os: windows
    pool:
      name: AzurePipelines-EO
      image: 1ESPT-Ubuntu22.04
      os: linux
    stages:
      - stage: Build
        jobs:
          - job: Build
            displayName: Build Function
            templateContext:
              outputs:
                - output: pipelineArtifact
                  displayName: "Publish Artifact"
                  targetPath: $(Build.ArtifactStagingDirectory)/telemetry.zip
                  artifactName: telemetry-drop
            steps:
              - checkout: self
              - task: UseDotNet@2
                displayName: Use .NET 8 SDK
                inputs:
                  version: 8.x
              - script: |
                  dotnet publish src/NetUpgradePlannerTelemetry/NetUpgradePlannerTelemetry.csproj -o "$(Build.ArtifactStagingDirectory)/publish" /p:SourceRevisionId=$(Build.SourceVersion)
                displayName: Publish Function
              - task: ArchiveFiles@2
                displayName: "Archive published files"
                inputs:
                  rootFolderOrFile: "$(Build.ArtifactStagingDirectory)/publish"
                  includeRootFolder: false
                  archiveType: "zip"
                  archiveFile: "$(Build.ArtifactStagingDirectory)/telemetry.zip"
                  replaceExistingArchive: true
              - script: |
                  rm -rf "$(Build.ArtifactStagingDirectory)/publish"
                displayName: "Clean up publish folder"
