trigger:
  branches:
    include:
      - main
  paths:
    include:
      - pipelines/build-planner.yml
      - src/NetUpgradePlanner/**
      - src/Terrajobst.ApiCatalog/**
      - src/Terrajobst.NetUpgradePlanner/**
      - src/Terrajobst.NetUpgradePlanner.Excel/**
      - src/Terrajobst.UsageCrawling/**

resources:
  repositories:
    - repository: self
      type: git
      ref: main
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: AzurePipelines-EO
      image: 1ESPT-Windows2022
      os: windows
    stages:
      - stage: Build
        jobs:
          - job: Build
            displayName: Build and Pack
            steps:
              - checkout: self
                fetchDepth: 0
              - task: UseDotNet@2
                displayName: Use .NET 8 SDK
                inputs:
                  version: 8.x
              - task: NuGetAuthenticate@1
                displayName: "NuGet Authenticate"
              - task: DotNetCoreCLI@2
                displayName: Install NBGV tool
                inputs:
                  command: custom
                  custom: tool
                  arguments: install -g nbgv --add-source "$(RestorePackageSource)" --ignore-failed-sources
              - script: nbgv cloud -p src/NetUpgradePlanner
                displayName: Set Version
              - script: |
                  cd src/NetUpgradePlanner
                  dotnet publish /p:SourceRevisionId=$(Build.SourceVersion)
                displayName: dotnet publish
              - powershell: |
                  mkdir .artifacts/squirrel-release
                  cd .artifacts/publish/NetUpgradePlanner

                  # Attempt to find Squirrel.exe in nuget cache
                  $squirrelPath = Get-ChildItem -Path "$env:USERPROFILE\.nuget\packages\clowd.squirrel" -Filter "Squirrel.exe" -Recurse | Select-Object -First 1 -ExpandProperty FullName
                  if (-not $squirrelPath) {
                      Write-Error "Squirrel.exe not found in nuget packages."
                      exit 1
                  }
                  Set-Alias Squirrel $squirrelPath

                  Squirrel http-down --url "https://$(StorageAccountName).blob.core.windows.net/squirrel/" -r "../../squirrel-release"
                  Squirrel pack --framework net6.0,vcredist143-x86 --packId "NetUpgradePlanner" --packTitle ".NET Upgrade Planner" --packVersion "$(NBGV_SemVer1)" --packAuthors "Immo Landwerth" --packDir "." -r "../../squirrel-release"
                displayName: Squirrel pack
                workingDirectory: $(Build.SourcesDirectory)
              - task: AzureCLI@2
                displayName: Upload release
                inputs:
                  azureSubscription: "$(AzureSubscriptionConnection)"
                  scriptType: "pscore"
                  scriptLocation: "inlineScript"
                  inlineScript: |
                    az storage blob upload-batch -d squirrel -s $(Build.SourcesDirectory)/.artifacts/squirrel-release --overwrite --account-name $(StorageAccountName) --auth-mode login
