trigger:
  branches:
    include:
      - release/nuget

resources:
  repositories:
    - repository: self
      type: git
      ref: main
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: AzurePipelines-EO
      image: 1ESPT-Windows2022
      os: windows
    stages:
      - stage: Build
        jobs:
          - job: Build
            displayName: Build and Publish
            steps:
              - checkout: self
                fetchDepth: 0
              - task: UseDotNet@2
                displayName: Use .NET 8 SDK
                inputs:
                  version: 8.x
              - task: NuGetAuthenticate@1
                displayName: "NuGet Authenticate"
              - script: |
                  cd src/
                  dotnet test
                displayName: Run tests
              - script: |
                  cd src/
                  dotnet publish /p:SourceRevisionId=$(Build.SourceVersion)
                displayName: Build packages
              - script: |
                  dotnet nuget push $(Build.SourcesDirectory)/.artifacts/package/bin/*.nupkg --source https://api.nuget.org/v3/index.json --api-key $(NuGetOrgToken) --skip-duplicate
                displayName: dotnet nuget push
