---
trigger:
  branches:
    include:
      - "*"
    exclude:
      - main
  paths:
    include:
      - pipelines/build-planner.yml
      - pipelines/templates/steps-build-planner.yml
      - src/NetUpgradePlanner/**
      - src/Terrajobst.ApiCatalog/**
      - src/Terrajobst.NetUpgradePlanner/**
      - src/Terrajobst.NetUpgradePlanner.Excel/**
      - src/Terrajobst.UsageCrawling/**
name: $(date:yyyyMMdd)$(rev:.r)
variables:
  BuildConfiguration: Release
resources:
  repositories:
    - repository: self
      type: git
      ref: main
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      codeql:
        compiled:
          enabled: true
    pool:
      name: AzurePipelines-EO
      image: 1ESPT-Windows2022
      os: windows
    customBuildTags:
      - ES365AIMigrationTooling
    stages:
      - stage: DeployPlanner
        jobs:
          - job: planner_tests
            displayName: Run planner tests
            steps:
              - checkout: self
              - task: UseDotNet@2
                displayName: Use .NET 8 SDK
                inputs:
                  version: 8.x
              - task: NuGetAuthenticate@1
                displayName: "NuGet Authenticate"
              - script: |
                  dotnet test src/Terrajobst.ApiCatalog.Tests/Terrajobst.ApiCatalog.Tests.csproj -c $(BuildConfiguration) --nologo
                  dotnet test src/Terrajobst.UsageCrawling.Tests/Terrajobst.UsageCrawling.Tests.csproj -c $(BuildConfiguration) --nologo
                  dotnet test src/Terrajobst.UsageCrawling.Storage.Tests/Terrajobst.UsageCrawling.Storage.Tests.csproj -c $(BuildConfiguration) --nologo
                displayName: "Run unit tests"
          - job: build_and_publish
            displayName: "Build and publish planner"
            dependsOn: planner_tests
            templateContext:
              outputs:
                - output: pipelineArtifact
                  displayName: "Publish planner release"
                  targetPath: $(Build.ArtifactStagingDirectory)/planner-release
                  artifactName: planner-release
            steps:
              - template: /pipelines/templates/steps-build-planner.yml@self
