trigger: none

resources:
  repositories:
    - repository: self
      type: git
      ref: main
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: AzurePipelines-EO
      image: 1ESPT-Windows2022
      os: windows
    stages:
      - stage: DownloadContainers
        jobs:
          - job: ContainerDownloader
            displayName: Download Blob Containers
            templateContext:
              outputs:
                - output: pipelineArtifact
                  displayName: "Downloaded Containers Artifact"
                  targetPath: $(build.artifactstagingdirectory)
                  artifactName: container-data
            steps:
              - checkout: self
                fetchDepth: 0
              - task: UseDotNet@2
                displayName: Use .NET 10 SDK
                inputs:
                  version: 10.x
              - task: NuGetAuthenticate@1
                displayName: "NuGet Authenticate"
              - task: AzureCLI@2
                displayName: Download containers
                inputs:
                  azureSubscription: "$(AzureSubscriptionConnection)"
                  scriptType: "pscore"
                  scriptLocation: "inlineScript"
                  inlineScript: |
                    cd src/ContainerDownloader
                    dotnet run
              - task: ArchiveFiles@2
                displayName: "Archive downloaded containers to container-downloads.zip"
                inputs:
                  rootFolderOrFile: "src/ContainerDownloader/downloads"
                  includeRootFolder: false
                  archiveType: "zip"
                  archiveFile: "$(build.artifactstagingdirectory)/container-downloads.zip"
                  replaceExistingArchive: true
              - script: |
                  rm -rf "src/ContainerDownloader/downloads"
                  echo "Deleted downloads folder"
                displayName: "Clean up downloads folder"
