trigger: none

schedules:
  - cron: "21 */6 * * *"
    displayName: Every 6 hours
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: self
      type: git
      ref: main
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: AzurePipelines-EO
      image: 1ESPT-Windows2022
      os: windows
    stages:
      - stage: GenerateUsage
        jobs:
          - job: GenUsageNuGet
            displayName: Generate NuGet Usage
            steps:
              - checkout: self
                fetchDepth: 0
              - task: UseDotNet@2
                displayName: Use .NET 8 SDK
                inputs:
                  version: 8.x
              - task: NuGetAuthenticate@1
                displayName: "NuGet Authenticate"
              - task: AzureCLI@2
                displayName: Generate NuGet usage
                inputs:
                  azureSubscription: "$(AzureSubscriptionConnection)"
                  scriptType: "pscore"
                  scriptLocation: "inlineScript"
                  inlineScript: |
                    cd src/GenUsageNuGet
                    dotnet run -- crawl
                env:
                  AzureStorageServiceUrl: $(AzureStorageServiceUrl)

          - job: GenUsagePlanner
            displayName: Generate Planner Usage
            steps:
              - checkout: self
                fetchDepth: 0
              - task: UseDotNet@2
                displayName: Use .NET 8 SDK
                inputs:
                  version: 8.x
              - task: NuGetAuthenticate@1
                displayName: "NuGet Authenticate"
              - task: AzureCLI@2
                displayName: Generate Planner usage
                inputs:
                  azureSubscription: "$(AzureSubscriptionConnection)"
                  scriptType: "pscore"
                  scriptLocation: "inlineScript"
                  inlineScript: |
                    cd src/GenUsagePlanner
                    dotnet run
                env:
                  AzureStorageServiceUrl: $(AzureStorageServiceUrl)

          - job: GenUsage
            displayName: Generate Usage
            dependsOn:
              - GenUsageNuGet
              - GenUsagePlanner
            steps:
              - checkout: self
                fetchDepth: 0
              - task: UseDotNet@2
                displayName: Use .NET 8 SDK
                inputs:
                  version: 8.x
              - task: AzureCLI@2
                displayName: Generate usage
                inputs:
                  azureSubscription: "$(AzureSubscriptionConnection)"
                  scriptType: "pscore"
                  scriptLocation: "inlineScript"
                  inlineScript: |
                    cd src/GenUsage
                    dotnet run
                env:
                  AzureStorageServiceUrl: $(AzureStorageServiceUrl)
                  ApisOfDotNetWebHookSecret: $(ApisOfDotNetWebHookSecret)
