trigger: 
  branches:
    include:
      - "*"
    exclude:
      - main
  paths:
    include:
      - src/GenCatalog/**
      - src/DumpPacks/**
      - src/Terrajobst.ApiCatalog/**
      - src/Terrajobst.ApiCatalog.ActionsRunner/**
      - src/Terrajobst.ApiCatalog.Generation/**
      - src/Terrajobst.ApiCatalog.SuffixTree/**
      - src/GenUsageNuGet/**
variables:
  - name: BuildConfiguration
    value: Release
name: $(date:yyyyMMdd)$(rev:.r)

resources:
  repositories:
    - repository: self
      type: git
      ref: main
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: AzurePipelines-EO
        image: 1ESPT-Windows2022
        os: windows
    pool:
      name: AzurePipelines-EO
      image: 1ESPT-Ubuntu22.04
      os: linux
    stages: 
      - stage: BuildAndPublishArtifact
        displayName: Build and Publish Artifact
        jobs:
        - job: generate_catalog_job
          displayName: "Build Catalog Generator Artifact"
          timeoutInMinutes: 0
          cancelTimeoutInMinutes: 5
          templateContext:
            outputs:
              - output: pipelineArtifact
                displayName: "Publish Catalog Artifact"
                targetPath: $(Build.ArtifactStagingDirectory)/gen-catalog-drop
                artifactName: gen-catalog-drop
          steps:
          - checkout: self
            clean: true
            fetchDepth: 0
          - task: UseDotNet@2
            displayName: "Install .NET 10"
            inputs:
              packageType: sdk
              version: 10.x
              includePreviewVersions: true
          - task: NuGetAuthenticate@1
            displayName: "NuGet Authenticate"
          - script: |
              dotnet publish "$(Build.SourcesDirectory)/src/GenCatalog/GenCatalog.csproj" \
                --configuration $(BuildConfiguration) \
                --output "$(Build.ArtifactStagingDirectory)/gen-catalog-drop/publish-gen-catalog"
            displayName: "Publish GenCatalog"
          - script: |
              dotnet publish "$(Build.SourcesDirectory)/src/DumpPacks/DumpPacks.csproj" \
                --configuration $(BuildConfiguration) \
                --output "$(Build.ArtifactStagingDirectory)/gen-catalog-drop/publish-dumppacks"
            displayName: "Publish DumpPacks"