---
trigger: none

name: $(date:yyyyMMdd)$(rev:.r)
variables:
  - name: BuildConfiguration
    value: Release
schedules:
  - cron: '21 */6 * * *' # At :21 in every 6th hour
    displayName: "Generate usage every 6 hours"
    branches:
      include:
        - main
    always: true
resources:
  repositories:
    - repository: self
      type: git
      ref: main
stages:
  - template: /pipelines/templates/stages-gen-usage.yml@self
    parameters:
      StageName: GenerateUsageDev
      StageDisplayName: Generate Usage Dev Artifact
      BuildType: dev
  - template: /pipelines/templates/stages-gen-usage.yml@self
    parameters:
      StageName: GenerateUsageProd
      StageDisplayName: Generate Usage Prod Artifact
      BuildType: prod