trigger: none

schedules:
  - cron: "21 12 * * *"
    displayName: Daily at 12:21 PM UTC
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: self
      type: git
      ref: main
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: AzurePipelines-EO
      image: 1ESPT-Windows2022
      os: windows
    stages:
      - stage: GenerateCatalog
        jobs:
          - job: GenCatalog
            displayName: Generate Catalog
            steps:
              - checkout: self
                fetchDepth: 0
              - task: UseDotNet@2
                displayName: Use .NET 8 SDK
                inputs:
                  version: 8.x
              - task: AzureCLI@2
                displayName: Generate catalog
                inputs:
                  azureSubscription: "$(AzureSubscriptionConnection)"
                  scriptType: "pscore"
                  scriptLocation: "inlineScript"
                  inlineScript: |
                    cd src/GenCatalog
                    dotnet run
                env:
                  AzureStorageServiceUrl: $(AzureStorageServiceUrl)
                  ApisOfDotNetWebHookSecret: $(ApisOfDotNetWebHookSecret)
