trigger: none

schedules:
  - cron: "5 21 * * 2,4"
    displayName: Tuesday and Thursday at 2:05 PM PT
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: self
      type: git
      ref: main
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: AzurePipelines-EO
      image: 1ESPT-Windows2022
      os: windows
    stages:
      - stage: GenerateDesignNotes
        jobs:
          - job: GenDesignNotes
            displayName: Generate Design Notes
            steps:
              - checkout: self
                fetchDepth: 0
              - task: UseDotNet@2
                displayName: Use .NET 8 SDK
                inputs:
                  version: 8.x
              - task: NuGetAuthenticate@1
                displayName: "NuGet Authenticate"
              - task: AzureCLI@2
                displayName: Generate design notes
                inputs:
                  azureSubscription: "$(AzureSubscriptionConnection)"
                  scriptType: "pscore"
                  scriptLocation: "inlineScript"
                  inlineScript: |
                    cd src/GenDesignNotes
                    dotnet run
                env:
                  AzureStorageServiceUrl: $(AzureStorageServiceUrl)
                  ApisOfDotNetWebHookSecret: $(ApisOfDotNetWebHookSecret)
