trigger: none
variables:
  BuildConfiguration: Release
schedules:
  - cron: "21 12 * * *"   # 12:21 PM UTC
    displayName: Daily 12:21 UTC
    branches:
      include:
        - main
    always: true

name: $(date:yyyyMMdd)$(rev:.r)

resources:
  repositories:
    - repository: self
      type: git
      ref: main

pool:
  name: AzurePipelines-EO
  image: 1ESPT-Windows2022
  os: windows
stages:
  - stage: generate_catalog
    displayName: "Generate Catalog"
    jobs:
      - job: generate_catalog_job
        displayName: "Run Catalog Generator"
        timeoutInMinutes: 60
        steps:
          - checkout: self
            fetchDepth: 0
          - task: UseDotNet@2
            displayName: "Install .NET 8"
            inputs:
              packageType: sdk
              version: 8.x
          - task: NuGetAuthenticate@1
            displayName: "NuGet Authenticate"
          - task: AzureCLI@2
            displayName: "Generate Catalog"
            inputs:
              azureSubscription: "$(AzureSubscriptionConnection)"
              scriptType: "bash"
              scriptLocation: "inlineScript"                  
              addSpnToEnvironment: true
              inlineScript: |
                export APISOFDOTNET_INDEX_PATH="$(Pipeline.Workspace)/catalog"
                mkdir -p "$APISOFDOTNET_INDEX_PATH"
                mkdir -p "$APISOFDOTNET_INDEX_PATH/index"
                mkdir -p "$APISOFDOTNET_INDEX_PATH/frameworks"
                mkdir -p "$APISOFDOTNET_INDEX_PATH/packs"
                mkdir -p "$APISOFDOTNET_INDEX_PATH/packages"
                cd "$(Build.SourcesDirectory)/src/GenCatalog"
                dotnet run --configuration $(BuildConfiguration)
            env:
              AzureStorageServiceUrl: $(AzureStorageServiceUrl)
              ApisOfDotNetWebHookSecret: $(ApisOfDotNetWebHookSecret)
              APISOFDOTNET_INDEX_PATH: $(Pipeline.Workspace)/catalog
