---
trigger: none

name: $(date:yyyyMMdd)$(rev:.r)
variables:
  - name: BuildConfiguration
    value: Debug
resources:
  repositories:
    - repository: self
      type: git
      ref: main
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

schedules:
  - cron: "5 21 * * 2,4" # At 21:05 on Tuesday and Thursday
    displayName: "Generate design notes every Tuesday and Thursday"
    branches:
      include:
        - main
    always: true

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      codeql:
        compiled:
          enabled: true
      baseline:
        baselineSet: default
        baselineBranch: main
    pool:
      name: AzurePipelines-EO
      image: 1ESPT-Windows2022
      os: windows
    customBuildTags:
      - ES365AIMigrationTooling
    stages:
      - stage: GenerateDesignNotes
        jobs:
          - job: generate_design_notes
            displayName: Generate design notes
            templateContext:
              outputs:
                - output: pipelineArtifact
                  displayName: "Pipeline artifact containing GenDesignNotes output"
                  targetPath: $(build.artifactstagingdirectory)/GenDesignNotesOutput
                  artifactName: WifGenDesignNotesOutput
            steps:
              - checkout: self
              - task: UseDotNet@2
                displayName: Use .NET 8 SDK
                inputs:
                  version: 8.x
              - task: NuGetAuthenticate@1
                displayName: "NuGet Authenticate"
              - script: |
                  dotnet build "$(Build.SourcesDirectory)/src/GenDesignNotes/GenDesignNotes.csproj" --configuration $(BuildConfiguration)
                displayName: "Build GenDesignNotes"
              - task: AzureCLI@2
                displayName: "Run GenDesignNotes"
                inputs:
                  azureSubscription: "$(AzureSubscriptionConnection)"
                  scriptType: "bash"
                  scriptLocation: "inlineScript"                  
                  addSpnToEnvironment: true
                  inlineScript: |
                    
                    echo "== az account =="
                    az account show -o jsonc

                    echo "== WIF vars (from addSpnToEnvironment) =="
                    mkdir -p "$(Build.ArtifactStagingDirectory)/GenDesignNotesOutput"
                    WIF_VARS_FILE="$(Build.ArtifactStagingDirectory)/GenDesignNotesOutput/wif-vars.txt"
                    env | grep -E 'servicePrincipalId|tenantId|idToken' > "$WIF_VARS_FILE" || true
                    echo "Saved WIF vars to: $WIF_VARS_FILE"
                    
                    echo "== can we get a Storage token? =="
                    az account get-access-token --resource https://storage.azure.com/ -o jsonc
 

                    cd "$(Build.SourcesDirectory)/src/GenDesignNotes"
                    dotnet run --configuration $(BuildConfiguration)
                env:
                  AzureStorageServiceUrl: $(AzureStorageServiceUrl)
                  ApisOfDotNetWebHookSecret: $(ApisOfDotNetWebHookSecret)
