trigger: none

schedules:
  - cron: "21 12 * * *"   # 12:21 PM UTC
    displayName: Daily 12:21 UTC
    branches:
      include:
        - main
    always: true

name: $(date:yyyyMMdd)$(rev:.r)

resources:
  repositories:
    - repository: self
      type: git
      ref: main
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      codeql:
        compiled:
          enabled: false
    pool:
      name: AzurePipelines-EO
      image: 1ESPT-Windows2022
      os: windows
    stages:
      - stage: generate_catalog
        displayName: "Generate Catalog"
        jobs:
          - job: generate_catalog_job
            displayName: "Run Catalog Generator"
            timeoutInMinutes: 60
            steps:
              - checkout: self
                fetchDepth: 0

              - task: UseDotNet@2
                displayName: "Install .NET 8"
                inputs:
                  packageType: sdk
                  version: 8.0.x

              - task: NuGetAuthenticate@1
                displayName: "NuGet Authenticate"

              - task: DotNetCoreCLI@2
                displayName: "Generate catalog"
                inputs:
                  azureSubscription: "$(AzureSubscriptionConnection)"
                  scriptType: "bash"
                  scriptLocation: "inlineScript"                  
                  addSpnToEnvironment: true
                  inlineScript: |
                    
                    echo "== az account =="
                    az account show -o jsonc

                    echo "== WIF vars (from addSpnToEnvironment) =="
                    mkdir -p "$(Build.ArtifactStagingDirectory)/GenCatalogOutput"
                    WIF_VARS_FILE="$(Build.ArtifactStagingDirectory)/GenCatalogOutput/wif-vars.txt"
                    env | grep -E 'servicePrincipalId|tenantId|idToken' > "$WIF_VARS_FILE" || true
                    echo "Saved WIF vars to: $WIF_VARS_FILE"
                    
                    echo "== can we get a Storage token? =="
                    az account get-access-token --resource https://storage.azure.com/ -o jsonc

                    Write-Host "Files:"
                    ls

                    cd "$(Build.SourcesDirectory)/src/GenCatalog"
                    dotnet run --configuration $(BuildConfiguration)
                env:
                  AzureStorageServiceUrl: $(AzureStorageServiceUrl)
                  ApisOfDotNetWebHookSecret: $(ApisOfDotNetWebHookSecret)
