trigger: none
name: $(Date:yyyyMMdd).$(Rev:r)

resources:
  pipelines:
    - pipeline: "apis-of-dotnet-telemetry-build"
      project: "OnlineServices"
      source: 'ASP-IIS-dotnet\builds\apis-of-dotnet-telemetry-build'
      trigger:
        branches:
          include:
            - main
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: AzurePipelines-EO
      image: 1ESPT-Ubuntu22.04
      os: linux
    stages:
      - stage: Dev
        displayName: Deploy to Dev
        jobs:
          - job: Deploy
            displayName: Deploy to Azure Function
            templateContext:
              type: releaseJob
              isProduction: false
              inputs:
                - input: pipelineArtifact
                  pipeline: "telemetry-build"
                  artifactName: "telemetry-drop"
                  targetPath: "$(Pipeline.Workspace)/telemetry-drop"
            steps:
              - task: AzureFunctionApp@1
                displayName: Deploy Azure Function
                inputs:
                  azureSubscription: "$(AzureDevSubscriptionConnection)"
                  appType: functionApp
                  appName: apisofdotnetplanner-dev
                  package: "$(Pipeline.Workspace)/telemetry-drop/telemetry.zip"
