trigger: none
name: $(Date:yyyyMMdd).$(Rev:r)
resources:
  pipelines:
    - pipeline: "apis-of-dotnet-build"
      project: "OnlineServices"
      source: 'ASP-IIS-dotnet\builds\apis-of-dotnet-build'
      trigger:
        branches:
          include:
            - main
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: AzurePipelines-EO
      image: 1ESPT-Ubuntu22.04
      os: linux
    stages:
      - stage: Dev
        displayName: Deploy to Dev
        jobs:
          - job: Job_1
            displayName: Run on agent
            condition: succeeded()
            timeoutInMinutes: 0
            templateContext:
              type: releaseJob
              isProduction: false
              inputs:
                - input: pipelineArtifact
                  pipeline: "apis-of-dotnet-build"
                  artifactName: "apis-of-dotnet-drop"
                  targetPath: "$(Pipeline.Workspace)/apis-of-dotnet-drop"
            steps:
              - task: AzureWebApp@1
                displayName: Deploy Web App
                inputs:
                  azureSubscription: "$(AzureDevSubscriptionConnection)"
                  appName: apisofdotnet-dev
                  appType: webAppLinux
                  package: $(Pipeline.Workspace)/apis-of-dotnet-drop/publish
