name: Deploy Site

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/deploy-site.yml
      - src/apisof.net/**
      - src/Terrajobst.ApiCatalog/**

env:
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0 # We need the full history in order to use Git versioning

    - name: Get .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '8.0.*'

    - name: dotnet publish
      run: |
        cd src/apisof.net
        dotnet publish /p:SourceRevisionId=${{ github.sha }}

    - name: Upload build
      uses: actions/upload-artifact@v5
      with:
        name: site
        path: .artifacts/publish/apisof.net

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Download build
      uses: actions/download-artifact@v6
      with:
        name: site
        path: .artifacts/publish/apisof.net

    - name: webapps-deploy
      uses: azure/webapps-deploy@v3
      with:
        app-name: apisofdotnet
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
        package: .artifacts/publish/apisof.net
